# Generated by Django 5.1.1 on 2024-09-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_faq_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='image',
        ),
        migrations.AddField(
            model_name='faq',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
